const defaultProducts = [
  {id:1,name:"سماعة بلوتوث",price:450,category:"electronics",emoji:"🎧",description:"سماعة بلوتوث لاسلكية بصوت واضح وتصميم مريح للاستخدام اليومي."},
  {id:2,name:"ساعة ذكية",price:850,category:"electronics",emoji:"⌚",description:"ساعة ذكية أنيقة لمتابعة الوقت والنشاط اليومي مع تصميم عملي."},
  {id:3,name:"تيشيرت كاجوال",price:320,category:"fashion",emoji:"👕",description:"تيشيرت كاجوال مريح مناسب للخروجات والاستخدام اليومي."},
  {id:4,name:"شنطة ظهر",price:390,category:"fashion",emoji:"🎒",description:"شنطة ظهر عملية لحمل الأدوات والمستلزمات بسهولة."},
  {id:5,name:"كوب حراري",price:220,category:"home",emoji:"☕",description:"كوب حراري مناسب للمشروبات الساخنة والباردة أثناء التنقل."},
  {id:6,name:"مصباح مكتب",price:280,category:"home",emoji:"💡",description:"مصباح مكتب بإضاءة مناسبة للمذاكرة والعمل والقراءة."},
  {id:7,name:"شاحن سريع",price:250,category:"electronics",emoji:"🔌",description:"شاحن سريع للاستخدام اليومي مع تصميم صغير وسهل الحمل."},
  {id:8,name:"حافظة هاتف",price:150,category:"electronics",emoji:"📱",description:"حافظة هاتف خفيفة تساعد على حماية الهاتف من الخدوش والصدمات البسيطة."}
];
const whatsappNumber = "201149902302";
const $ = id => document.getElementById(id);
const money = n => `${Number(n).toLocaleString("ar-EG")} ج.م`;
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[c]));
function readJson(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch { return fallback; } }
let products = readJson("loqataProducts", defaultProducts); if (!Array.isArray(products) || !products.length) products = defaultProducts;
let cart = readJson("loqataCart", []); if (!Array.isArray(cart)) cart = [];
let orders = readJson("loqataOrders", []); if (!Array.isArray(orders)) orders = [];
let currentCategory = "all";
const categoryNames = {electronics:"إلكترونيات",fashion:"ملابس",home:"المنزل"};
function saveCart(){localStorage.setItem("loqataCart",JSON.stringify(cart));}
function saveProducts(){localStorage.setItem("loqataProducts",JSON.stringify(products));}
function saveOrders(){localStorage.setItem("loqataOrders",JSON.stringify(orders));}
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),1800);}
function renderProducts(){const q=$("searchInput").value.trim().toLowerCase();const filtered=products.filter(p=>(currentCategory==="all"||p.category===currentCategory)&&p.name.toLowerCase().includes(q));$("products").innerHTML=filtered.map(p=>`<article class="card"><div class="product-img" aria-hidden="true">${escapeHtml(p.emoji)}</div><div class="card-body"><h3>${escapeHtml(p.name)}</h3><div class="price">${money(p.price)}</div><button class="details-btn" data-details="${p.id}" type="button">عرض التفاصيل</button><button class="add-btn" data-add="${p.id}" type="button">أضف للسلة</button></div></article>`).join("");$("resultCount").textContent=`${filtered.length} منتج`;$('emptyState').classList.toggle('hidden',filtered.length!==0);}
function cartCount(){return cart.reduce((s,i)=>s+i.qty,0)}
function cartTotal(){return cart.reduce((s,i)=>s+i.qty*i.price,0)}
function renderCart(){$("cartCount").textContent=cartCount();$("cartTotal").textContent=money(cartTotal());$("cartItems").innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><div class="cart-emoji">${escapeHtml(i.emoji)}</div><div class="cart-info"><strong>${escapeHtml(i.name)}</strong><div>${money(i.price)}</div><div class="qty"><button type="button" data-minus="${i.id}">−</button><span>${i.qty}</span><button type="button" data-plus="${i.id}">+</button><button class="remove" type="button" data-remove="${i.id}">حذف</button></div></div></div>`).join(""):`<div class="empty">السلة فارغة حاليًا.</div>`;}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...p,qty:1});saveCart();renderCart();toast("تمت إضافة المنتج للسلة");}
function changeQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();renderCart();}
function openCart(){$("cartPanel").classList.add("open");$("cartOverlay").classList.remove("hidden");}
function closeCart(){$("cartPanel").classList.remove("open");$("cartOverlay").classList.add("hidden");}
function openProductDetails(id){const p=products.find(x=>x.id===id);if(!p)return;$("productDetails").innerHTML=`<div class="detail-emoji">${escapeHtml(p.emoji)}</div><div class="detail-content"><h3>${escapeHtml(p.name)}</h3><div class="detail-price">${money(p.price)}</div><p>${escapeHtml(p.description||"منتج مختار من متجر لقطة.")}</p><button class="primary-btn" data-detail-add="${p.id}" type="button">🛒 أضف للسلة</button></div>`;$("productModal").hidden=false;$("productOverlay").classList.remove("hidden");document.body.classList.add("modal-open");}
function closeProductDetails(){$("productModal").hidden=true;$("productOverlay").classList.add("hidden");document.body.classList.remove("modal-open");}
function openCheckout(){if(!cart.length)return toast("أضف منتجًا إلى السلة أولًا");$("checkoutSummary").innerHTML=`<strong>ملخص الطلب</strong>${cart.map(i=>`<div>${escapeHtml(i.name)} × ${i.qty} — ${money(i.qty*i.price)}</div>`).join("")}<hr><strong>الإجمالي: ${money(cartTotal())}</strong>`;$("checkoutModal").hidden=false;$("checkoutOverlay").classList.remove("hidden");document.body.classList.add("modal-open");}
function closeCheckout(){$("checkoutModal").hidden=true;$("checkoutOverlay").classList.add("hidden");document.body.classList.remove("modal-open");}
function sendOrder(name,phone,address){const order={id:Date.now(),date:new Date().toLocaleString("ar-EG"),name,phone,address,items:cart.map(i=>({name:i.name,qty:i.qty,price:i.price})),total:cartTotal(),status:"جديد"};orders.unshift(order);saveOrders();const lines=cart.map(i=>`- ${i.name} × ${i.qty} = ${money(i.qty*i.price)}`);const message=`مرحبًا، أريد تأكيد طلبي من متجر لقطة:\n\nالاسم: ${name}\nالهاتف: ${phone}\nالعنوان: ${address}\n\nالمنتجات:\n${lines.join("\n")}\n\nالإجمالي: ${money(cartTotal())}`;window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer");toast("تم حفظ الطلب وتجهيزه لواتساب");closeCheckout();}
function closeSettingsMenu(){$("settingsMenu").hidden=true;$('menuBtn').setAttribute('aria-expanded','false');}
function toggleSettingsMenu(){const menu=$("settingsMenu");menu.hidden=!menu.hidden;$("menuBtn").setAttribute("aria-expanded",String(!menu.hidden));}
function handleSetting(action){closeSettingsMenu();if(action==="home")window.scrollTo({top:0,behavior:"smooth"});else if(action==="clear-cart"){cart=[];saveCart();renderCart();toast("تم تفريغ السلة");}else if(action==="about")toast("لقطة — متجر إلكتروني لمنتجات مختارة");else if(action==="contact")window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent("مرحبًا، أريد التواصل مع متجر لقطة")}`,"_blank");else if(action==="admin")openAdmin();}
function renderAdmin(){
  $("adminStats").innerHTML=`<div>عدد المنتجات: <strong>${products.length}</strong></div><div>عدد الطلبات: <strong>${orders.length}</strong></div><div>إجمالي الطلبات: <strong>${money(orders.reduce((s,o)=>s+Number(o.total||0),0))}</strong></div><div>طلبات جديدة: <strong>${orders.filter(o=>o.status==="جديد").length}</strong></div>`;
  $("adminProducts").innerHTML=products.map(p=>`<div class="admin-product-card"><div class="admin-product-grid"><div class="admin-product-preview"><span>${escapeHtml(p.emoji)}</span><strong>${escapeHtml(p.name)}</strong></div><label>الاسم<input data-field="name" data-product-id="${p.id}" value="${escapeHtml(p.name)}"></label><label>السعر<input type="number" min="0" data-field="price" data-product-id="${p.id}" value="${p.price}"></label><label>القسم<select data-field="category" data-product-id="${p.id}"><option value="electronics" ${p.category==='electronics'?'selected':''}>إلكترونيات</option><option value="fashion" ${p.category==='fashion'?'selected':''}>ملابس</option><option value="home" ${p.category==='home'?'selected':''}>المنزل</option></select></label><label>الإيموجي<input data-field="emoji" data-product-id="${p.id}" value="${escapeHtml(p.emoji)}"></label><label class="wide-field">الوصف<textarea data-field="description" data-product-id="${p.id}" rows="2">${escapeHtml(p.description||'')}</textarea></label></div><div class="admin-actions"><button type="button" data-save-product="${p.id}">حفظ التعديلات</button><button type="button" class="danger-btn" data-delete-product="${p.id}">حذف المنتج</button></div></div>`).join("");
  const filter=$("orderStatusFilter")?.value||"all";const visible=orders.filter(o=>filter==="all"||o.status===filter);
  $("adminOrders").innerHTML=visible.length?visible.map(o=>`<details class="order-card"><summary>#${o.id} — ${escapeHtml(o.name)} — ${money(o.total)} — <span class="status-pill status-${o.status==='جديد'?'new':o.status==='مكتمل'?'done':o.status==='ملغي'?'cancelled':'progress'}">${escapeHtml(o.status||'جديد')}</span></summary><p>الهاتف: ${escapeHtml(o.phone)}<br>العنوان: ${escapeHtml(o.address)}<br>التاريخ: ${escapeHtml(o.date)}</p><div>${(o.items||[]).map(i=>`<div>${escapeHtml(i.name)} × ${i.qty} — ${money(i.qty*i.price)}</div>`).join("")}</div><label class="order-status-editor">حالة الطلب<select data-order-status-select="${o.id}"><option ${o.status==='جديد'?'selected':''}>جديد</option><option ${o.status==='قيد التجهيز'?'selected':''}>قيد التجهيز</option><option ${o.status==='تم الشحن'?'selected':''}>تم الشحن</option><option ${o.status==='مكتمل'?'selected':''}>مكتمل</option><option ${o.status==='ملغي'?'selected':''}>ملغي</option></select></label><button type="button" class="danger-btn" data-delete-order="${o.id}">حذف الطلب</button></details>`).join(""):`<p class="empty">لا توجد طلبات بهذه الحالة.</p>`;
}
function openAdmin(){renderAdmin();$("adminModal").hidden=false;$("adminOverlay").classList.remove("hidden");document.body.classList.add("modal-open");}
function closeAdmin(){$("adminModal").hidden=true;$("adminOverlay").classList.add("hidden");document.body.classList.remove("modal-open");}

document.addEventListener("click",e=>{const add=e.target.closest("[data-add]");if(add){addToCart(Number(add.dataset.add));return;}const details=e.target.closest("[data-details]");if(details){openProductDetails(Number(details.dataset.details));return;}const detailAdd=e.target.closest("[data-detail-add]");if(detailAdd){addToCart(Number(detailAdd.dataset.detailAdd));closeProductDetails();return;}const plus=e.target.closest("[data-plus]");if(plus){changeQty(Number(plus.dataset.plus),1);return;}const minus=e.target.closest("[data-minus]");if(minus){changeQty(Number(minus.dataset.minus),-1);return;}const remove=e.target.closest("[data-remove]");if(remove){cart=cart.filter(x=>x.id!==Number(remove.dataset.remove));saveCart();renderCart();return;}const setting=e.target.closest("[data-setting]");if(setting){handleSetting(setting.dataset.setting);return;}const cat=e.target.closest(".cat");if(cat){document.querySelectorAll(".cat").forEach(b=>b.classList.remove("active"));cat.classList.add("active");currentCategory=cat.dataset.category;renderProducts();return;}const saveProduct=e.target.closest("[data-save-product]");if(saveProduct){const id=Number(saveProduct.dataset.saveProduct);const p=products.find(x=>x.id===id);if(!p)return;document.querySelectorAll(`[data-product-id="${id}"]`).forEach(el=>{if(el.dataset.field==='price')p.price=Math.max(0,Number(el.value)||0);else if(el.dataset.field)p[el.dataset.field]=el.value.trim();});p.name=p.name||'منتج بدون اسم';p.emoji=p.emoji||'🛍️';saveProducts();cart=cart.map(i=>i.id===id?{...i,...p}:i);saveCart();renderProducts();renderCart();renderAdmin();toast('تم حفظ تفاصيل المنتج');return;}const del=e.target.closest("[data-delete-product]");if(del){const id=Number(del.dataset.deleteProduct);products=products.filter(p=>p.id!==id);cart=cart.filter(i=>i.id!==id);saveProducts();saveCart();renderProducts();renderCart();renderAdmin();toast('تم حذف المنتج');return;}const delOrder=e.target.closest('[data-delete-order]');if(delOrder){const id=Number(delOrder.dataset.deleteOrder);orders=orders.filter(o=>o.id!==id);saveOrders();renderAdmin();toast('تم حذف الطلب');return;}});

document.addEventListener('change',e=>{const select=e.target.closest('[data-order-status-select]');if(select){const o=orders.find(x=>x.id===Number(select.dataset.orderStatusSelect));if(o){o.status=select.value;saveOrders();renderAdmin();toast('تم تحديث حالة الطلب');}}if(e.target.id==='orderStatusFilter')renderAdmin();});
$("searchInput").addEventListener("input",renderProducts);$("menuBtn").addEventListener("click",toggleSettingsMenu);document.addEventListener("click",e=>{if(!e.target.closest(".topbar-actions"))closeSettingsMenu();});
$("closeProduct").addEventListener("click",closeProductDetails);$("productOverlay").addEventListener("click",closeProductDetails);$("cartBtn").addEventListener("click",openCart);$("closeCart").addEventListener("click",closeCart);$("cartOverlay").addEventListener("click",closeCart);$("saveCart").addEventListener("click",()=>{saveCart();toast("تم حفظ السلة على هذا الجهاز");});$("orderWhatsApp").addEventListener("click",openCheckout);$("closeCheckout").addEventListener("click",closeCheckout);$("checkoutOverlay").addEventListener("click",closeCheckout);
$("checkoutForm").addEventListener("submit",e=>{e.preventDefault();const name=$("customerName").value.trim(),phone=$("customerPhone").value.trim(),address=$("customerAddress").value.trim();if(!name||!phone||!address)return toast("من فضلك أكمل بيانات الطلب");sendOrder(name,phone,address);});
$("closeAdmin").addEventListener("click",closeAdmin);$("adminOverlay").addEventListener("click",closeAdmin);
$("addProductForm").addEventListener("submit",e=>{e.preventDefault();const name=$("newProductName").value.trim(),price=Number($("newProductPrice").value),category=$("newProductCategory").value,emoji=$("newProductEmoji").value.trim()||"🛍️",description=$("newProductDescription").value.trim()||"منتج جديد من متجر لقطة.";if(!name||!Number.isFinite(price)||price<0)return toast('تحقق من بيانات المنتج');products.push({id:Date.now(),name,price,category,emoji,description});saveProducts();renderProducts();renderAdmin();e.target.reset();toast('تمت إضافة المنتج');});
$("clearOrdersBtn").addEventListener('click',()=>{const before=orders.length;orders=orders.filter(o=>o.status!=='مكتمل');saveOrders();renderAdmin();toast(before===orders.length?'لا توجد طلبات مكتملة':'تم حذف الطلبات المكتملة');});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeProductDetails();closeCheckout();closeAdmin();closeSettingsMenu();}});renderProducts();renderCart();
